import type {
  Workflow,
  Document,
  WorkflowRun,
  AIInsight,
  WorkflowNode,
  WorkflowEdge,
  Organization,
  OrganizationMember,
  User,
} from "@/types";

export const mockUser: User = {
  id: "usr_1",
  email: "alex@acmecorp.com",
  full_name: "Alex Chen",
  is_active: true,
  is_superuser: false,
  created_at: "2025-08-12T10:00:00Z",
  updated_at: "2026-06-10T14:30:00Z",
};

export const mockOrganization: Organization = {
  id: "org_1",
  name: "Acme Corp",
  slug: "acme-corp",
  created_at: "2025-08-12T10:00:00Z",
  updated_at: "2026-06-10T14:30:00Z",
};

export const mockMembers: OrganizationMember[] = [
  {
    id: "om_1",
    user_id: "usr_1",
    organization_id: "org_1",
    role: "ADMIN",
    created_at: "2025-08-12T10:00:00Z",
  },
  {
    id: "om_2",
    user_id: "usr_2",
    organization_id: "org_1",
    role: "MEMBER",
    created_at: "2025-08-15T12:00:00Z",
  },
  {
    id: "om_3",
    user_id: "usr_3",
    organization_id: "org_1",
    role: "MEMBER",
    created_at: "2025-09-01T08:00:00Z",
  },
];

export const mockWorkflowNodes: WorkflowNode[] = [
  { id: "node_1", type: "trigger", label: "File Upload", position: { x: 50, y: 200 }, config: {} },
  { id: "node_2", type: "ai_action", label: "Extract Data", position: { x: 300, y: 200 }, config: { model: "gpt-4o", fields: ["total", "date", "vendor"] } },
  { id: "node_3", type: "condition", label: "Amount > $1000", position: { x: 550, y: 200 }, config: { field: "total", operator: ">", value: 1000 } },
  { id: "node_4", type: "output", label: "Send to Accounting", position: { x: 800, y: 100 }, config: { integration: "quickbooks" } },
  { id: "node_5", type: "output", label: "Flag for Review", position: { x: 800, y: 300 }, config: { integration: "email", address: "finance@acmecorp.com" } },
];

export const mockWorkflowEdges: WorkflowEdge[] = [
  { id: "edge_1", source: "node_1", target: "node_2" },
  { id: "edge_2", source: "node_2", target: "node_3" },
  { id: "edge_3", source: "node_3", target: "node_4", label: "Yes" },
  { id: "edge_4", source: "node_3", target: "node_5", label: "No" },
];

export const mockWorkflows: Workflow[] = [
  {
    id: "wf_1",
    name: "Invoice Processing Pipeline",
    organization_id: "org_1",
    description: "Extract data from incoming invoices and post to accounting",
    status: "active",
    trigger_type: "document_uploaded",
    is_active: true,
    workflow_definition: {
      nodes: mockWorkflowNodes,
      edges: mockWorkflowEdges,
    },
    created_at: "2026-01-10T09:00:00Z",
    updated_at: "2026-06-11T11:00:00Z",
    last_run: "2026-06-14T08:30:00Z",
    run_count: 847,
  },
  {
    id: "wf_2",
    name: "Email Classification & Routing",
    organization_id: "org_1",
    description: "Auto-classify support emails and route to appropriate teams",
    status: "active",
    trigger_type: "webhook",
    is_active: true,
    workflow_definition: null,
    created_at: "2026-02-15T10:00:00Z",
    updated_at: "2026-06-12T09:00:00Z",
    last_run: "2026-06-14T07:45:00Z",
    run_count: 2314,
  },
  {
    id: "wf_3",
    name: "Resume Screening Assistant",
    organization_id: "org_1",
    description: "Analyze candidate resumes and rank by job fit score",
    status: "draft",
    trigger_type: "manual",
    is_active: false,
    workflow_definition: null,
    created_at: "2026-04-20T14:00:00Z",
    updated_at: "2026-06-10T16:00:00Z",
    run_count: 12,
  },
  {
    id: "wf_4",
    name: "Contract Review Automation",
    organization_id: "org_1",
    description: "Review legal contracts for key clauses and risk factors",
    status: "active",
    trigger_type: "document_uploaded",
    is_active: true,
    workflow_definition: null,
    created_at: "2026-03-01T11:00:00Z",
    updated_at: "2026-06-13T10:00:00Z",
    last_run: "2026-06-14T06:00:00Z",
    run_count: 523,
  },
  {
    id: "wf_5",
    name: "Customer Onboarding Flow",
    organization_id: "org_1",
    description: "Send personalized onboarding emails and create CRM entries",
    status: "draft",
    trigger_type: "manual",
    is_active: false,
    workflow_definition: null,
    created_at: "2026-05-05T08:00:00Z",
    updated_at: "2026-06-09T12:00:00Z",
    run_count: 0,
  },
  {
    id: "wf_6",
    name: "Expense Report Analyzer",
    organization_id: "org_1",
    description: "Extract and categorize expenses from uploaded receipts",
    status: "active",
    trigger_type: "document_uploaded",
    is_active: true,
    workflow_definition: null,
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-06-13T15:00:00Z",
    last_run: "2026-06-14T09:00:00Z",
    run_count: 1567,
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc_1",
    title: "Q2 Financial Report",
    filename: "q2_financial_report.pdf",
    file_type: "application/pdf",
    file_size: 2450000,
    status: "done",
    organization_id: "org_1",
    uploaded_by: "usr_1",
    created_at: "2026-06-13T10:00:00Z",
  },
  {
    id: "doc_2",
    title: "Client Contract - TechCorp",
    filename: "techcorp_contract.pdf",
    file_type: "application/pdf",
    file_size: 1200000,
    status: "done",
    organization_id: "org_1",
    uploaded_by: "usr_1",
    created_at: "2026-06-12T14:00:00Z",
  },
  {
    id: "doc_3",
    title: "Invoice #INV-2026-0421",
    filename: "invoice_0421.pdf",
    file_type: "application/pdf",
    file_size: 890000,
    status: "done",
    organization_id: "org_1",
    uploaded_by: "usr_1",
    created_at: "2026-06-11T09:00:00Z",
  },
  {
    id: "doc_4",
    title: "Candidate Resume - Sarah Lee",
    filename: "sarah_lee_resume.pdf",
    file_type: "application/pdf",
    file_size: 450000,
    status: "processing",
    organization_id: "org_1",
    uploaded_by: "usr_1",
    created_at: "2026-06-14T09:30:00Z",
  },
  {
    id: "doc_5",
    title: "Support Email Dump",
    filename: "support_emails.csv",
    file_type: "text/csv",
    file_size: 3200000,
    status: "failed",
    organization_id: "org_1",
    uploaded_by: "usr_1",
    created_at: "2026-06-10T16:00:00Z",
  },
];

export const mockWorkflowRuns: WorkflowRun[] = [
  {
    id: "run_1",
    workflow_id: "wf_1",
    status: "completed",
    started_at: "2026-06-14T08:30:00Z",
    completed_at: "2026-06-14T08:32:15Z",
    logs: [
      {
        id: "log_1",
        run_id: "run_1",
        level: "info",
        message: "Workflow started",
        created_at: "2026-06-14T08:30:00Z",
      },
      {
        id: "log_2",
        run_id: "run_1",
        level: "info",
        message: "Document processed: invoice_0421.pdf",
        node_id: "node_2",
        created_at: "2026-06-14T08:31:00Z",
      },
      {
        id: "log_3",
        run_id: "run_1",
        level: "info",
        message: "Data extracted: 12 fields",
        node_id: "node_3",
        created_at: "2026-06-14T08:31:30Z",
      },
      {
        id: "log_4",
        run_id: "run_1",
        level: "info",
        message: "Output sent to accounting system",
        node_id: "node_5",
        created_at: "2026-06-14T08:32:15Z",
      },
    ],
  },
  {
    id: "run_2",
    workflow_id: "wf_1",
    status: "running",
    started_at: "2026-06-14T09:00:00Z",
    logs: [
      {
        id: "log_5",
        run_id: "run_2",
        level: "info",
        message: "Workflow started",
        created_at: "2026-06-14T09:00:00Z",
      },
      {
        id: "log_6",
        run_id: "run_2",
        level: "info",
        message: "Processing document: Q2 Financial Report",
        node_id: "node_2",
        created_at: "2026-06-14T09:01:00Z",
      },
    ],
  },
  {
    id: "run_3",
    workflow_id: "wf_1",
    status: "failed",
    started_at: "2026-06-13T22:00:00Z",
    completed_at: "2026-06-13T22:01:30Z",
    logs: [
      {
        id: "log_7",
        run_id: "run_3",
        level: "info",
        message: "Workflow started",
        created_at: "2026-06-13T22:00:00Z",
      },
      {
        id: "log_8",
        run_id: "run_3",
        level: "error",
        message: "Failed to parse document: unsupported format",
        node_id: "node_2",
        created_at: "2026-06-13T22:01:30Z",
      },
    ],
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: "insight_1",
    title: "Invoice Total Trends",
    description: "Average invoice value increased 23% this quarter compared to last",
    type: "extraction",
    document_id: "doc_3",
    created_at: "2026-06-14T08:00:00Z",
  },
  {
    id: "insight_2",
    title: "Contract Risk Detected",
    description:
      "Indemnification clause missing in TechCorp agreement — review recommended",
    type: "classification",
    document_id: "doc_2",
    created_at: "2026-06-13T12:00:00Z",
  },
  {
    id: "insight_3",
    title: "Q2 Report Summary",
    description:
      "Revenue grew 18% YoY. Operating costs decreased 5%. Strong cash position.",
    type: "summary",
    document_id: "doc_1",
    created_at: "2026-06-13T11:00:00Z",
  },
  {
    id: "insight_4",
    title: "Candidate Fit Analysis",
    description:
      "Sarah Lee ranks in top 5% for Senior Engineer role based on skill match",
    type: "classification",
    document_id: "doc_4",
    created_at: "2026-06-14T09:35:00Z",
  },
];
